import React from 'react';
import { Card } from '../components/common/Card';
import { ShieldCheck, AlertTriangle, Scale, Lock, Eye, FileText } from 'lucide-react';

export const ResponsibleAiPage: React.FC = () => {
  return (
    <div className="space-y-6">
      {/* Top Banner Header */}
      <div className="bg-[#0B0D10] border border-[#202630] rounded-md p-6 space-y-2">
        <div className="flex items-center gap-2 text-xs font-mono text-[#3B82F6] font-semibold uppercase tracking-wider">
          <ShieldCheck size={16} />
          <span>GOVERNANCE & ETHICAL AI FRAMEWORK</span>
        </div>
        <h1 className="text-xl sm:text-2xl font-semibold text-[#F4F1EA] tracking-wide">
          RESPONSIBLE AI & CLINICAL ETHICS
        </h1>
        <p className="text-xs text-[#8D949F] max-w-3xl leading-relaxed">
          MindPulse adheres to strict ethical AI standards, clinical decision support principles, data privacy protection, and transparent model governance.
        </p>
      </div>

      {/* Primary Clinical Notice Disclaimer */}
      <div className="bg-amber-950/40 border border-amber-800/60 rounded-md p-6 flex items-start gap-4">
        <AlertTriangle size={24} className="text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <h2 className="text-sm font-semibold text-amber-300 uppercase tracking-wider font-mono">
            CLINICAL NOTICE & DISCLAIMER
          </h2>
          <p className="text-sm text-[#F4F1EA] font-semibold">
            "This system provides AI-assisted analysis and is not a clinical diagnosis."
          </p>
          <p className="text-xs text-[#8D949F] leading-relaxed pt-1">
            MindPulse is engineered exclusively as a decision support research tool for clinical professionals. It does not replace independent evaluation, professional clinical judgment, or standardized diagnostic interviews.
          </p>
        </div>
      </div>

      {/* 4 Core Pillars of Governance */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="space-y-3">
          <div className="flex items-center gap-2 text-[#3B82F6] font-mono text-xs font-semibold border-b border-[#202630] pb-2">
            <Scale size={16} />
            <span>1. PROBABILISTIC INFERENCE</span>
          </div>
          <p className="text-xs text-[#8D949F] leading-relaxed">
            All AI model outputs generated by MindPulse are statistical probability estimates derived from latent feature distributions. Scores represent relative pattern alignment and must never be interpreted as definitive diagnostic truth.
          </p>
        </Card>

        <Card className="space-y-3">
          <div className="flex items-center gap-2 text-[#60A5FA] font-mono text-xs font-semibold border-b border-[#202630] pb-2">
            <Eye size={16} />
            <span>2. CONFIDENCE VS CERTAINTY</span>
          </div>
          <p className="text-xs text-[#8D949F] leading-relaxed">
            Model confidence metrics measure mathematical consistency within the feature space. High model confidence does not equate to clinical certainty and must be validated against standardized psychometric benchmarks.
          </p>
        </Card>

        <Card className="space-y-3">
          <div className="flex items-center gap-2 text-emerald-400 font-mono text-xs font-semibold border-b border-[#202630] pb-2">
            <FileText size={16} />
            <span>3. DATA QUALITY SENSITIVITY</span>
          </div>
          <p className="text-xs text-[#8D949F] leading-relaxed">
            Multimodal fusion fidelity relies directly on input quality. Poor lighting in camera feeds, acoustic noise in vocal recordings, or missing biophysical values will increase variance and lower prediction precision.
          </p>
        </Card>

        <Card className="space-y-3">
          <div className="flex items-center gap-2 text-amber-400 font-mono text-xs font-semibold border-b border-[#202630] pb-2">
            <Lock size={16} />
            <span>4. PRIVACY & LOCAL PROCESSING</span>
          </div>
          <p className="text-xs text-[#8D949F] leading-relaxed">
            Camera frames and audio buffers are processed client-side via throttled local streams. Raw media streams are never stored permanently without explicit consent and encrypted user transmission.
          </p>
        </Card>
      </div>
    </div>
  );
};
